site_name: jkphl/elevator
site_description: Elevator pattern — type casting of user defined objects in PHP
site_author: Joschi Kuphal
repo_url: https://github.com/jkphl/elevator
docs_dir: doc
pages:
- Home: 'index.md'
- To-Do: 'todo.md'
