site_name: jkphl/elevator
site_description: Elevator pattern implementation for PHP projects
site_author: Joschi Kuphal
repo_url: https://github.com/jkphl/elevator
docs_dir: doc
pages:
- Home: 'index.md'
- To-Do: 'todo.md'
